# Generated by Django 4.1.7 on 2023-03-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idflower', models.IntegerField(verbose_name='Id Товара')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена Товара')),
                ('notes', models.TextField(verbose_name='Описание')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='Фото')),
            ],
        ),
    ]
