# Generated by Django 4.1.7 on 2023-04-15 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(blank=True, max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'ordering': ['Tittle'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(blank=True, max_length=100, verbose_name='Название подкатегории')),
                ('Cat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Основная категория')),
            ],
            options={
                'verbose_name': 'Подкатегории',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['Tittle'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patronymic', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('Photo', models.ImageField(blank=True, upload_to='avatar/%Y/%m/%d/', verbose_name='Аватар')),
                ('Prof_User', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
            ],
            options={
                'verbose_name': 'Доп информация о пользователе',
                'verbose_name_plural': 'Доп информация о пользователе',
                'ordering': ['Prof_User'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(blank=True, max_length=100, verbose_name='Название товара')),
                ('Text', models.TextField(blank=True, max_length=1500, verbose_name='Текст товара')),
                ('Photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фотография товара')),
                ('Price', models.IntegerField(blank=True, verbose_name='Цена товара')),
                ('SubCat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'ordering': ['Tittle', 'SubCat', 'Price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True, verbose_name='Количество')),
                ('Status', models.CharField(blank=True, max_length=50, verbose_name='Статус')),
                ('Order_Prod', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Заказанный товар')),
                ('Order_User', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['Order_User'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(blank=True, max_length=100, verbose_name='Название категории')),
                ('Text', models.TextField(blank=True, max_length=1500, verbose_name='Текст комментария')),
                ('Date_Of_Change', models.DateField(blank=True, verbose_name='Дата изменения')),
                ('Rating', models.IntegerField(blank=True, verbose_name='Рейтинг')),
                ('Order_Prod', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Комментируемый товар')),
                ('Order_User', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['Tittle', 'Order_User', 'Order_Prod', 'Date_Of_Change', 'Rating'],
            },
        ),
    ]
